#!/usr/bin/env sh

# shellcheck source=/dev/null
. "$(dirname "$0")/_/husky.sh"

printf "\n3. Lint Commit Message: (commitlint-msg)"
commitlint --config conventions/.commitlintrc.yml --edit "$HUSKY_GIT_PARAMS"

cd "$current_working_dir" || return
printf "\n Done"
