#!/usr/bin/env sh

# shellcheck source=/dev/null
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

printf "\nPre Push Steps: (pre-push) : Test Suite"

# load .env
export "$(cat .env | xargs)"
printf "\n(pre-push) LWC - Threat Index : Unit Test"
make cover
