#!/usr/bin/env sh

# shellcheck source=/dev/null
. "$(dirname "$0")/_/husky.sh"
. "$(dirname "$0")/common.sh"

printf "\nPre Push Steps: (pre-push) : Test Suite"

# load .env
# shellcheck disable=SC2002
export "$(cat .env | xargs)"
make cover
